#!/bin/bash

# Script that runs following an install of Orchard rebranded munkitools pkg
# Sets various defaults on the client

# Set Prefs Plist

MUNKI_PREFS="/Library/Preferences/ManagedInstalls"

# Set Root Plist

ROOT_PREFS="/private/var/root/Library/Preferences/ManagedInstalls"

# Set Log dir

LOGDIR="/private/var/log/munki"

# Get UUID for client identifier

UUID=$(system_profiler SPHardwareDataType | awk '/UUID/ { print $3; }')

# Set Munki Repo

defaults write $MUNKI_PREFS SoftwareRepoURL https://munki.acme.com/production

# Set client identifier to be UUID

defaults write $MUNKI_PREFS ClientIdentifier $UUID

# Set Basic AuthV

defaults write $ROOT_PREFS AdditionalHttpHeaders -array "Authorization: Basic $BASIC_AUTH"

# Set basic auth hash

BASIC_AUTH="base64encodedpassword"

# Log to syslog

defaults write $MUNKI_PREFS LogToSyslog -bool true

# Change default log location

[ -d $LOGDIR ] || mkdir -p $LOGDIR 
touch $LOGDIR/Install.log
defaults write $MUNKI_PREFS LogFile $LOGDIR/managedsoftwareupdate.log

# Change help URL for Software Centre

defaults write $MUNKI_PREFS HelpURL https://docs.acme.com/OrchardSoftwareCentre

# Add icon to Dock if dockutil available

if [ -f /usr/local/bin/dockutil ]; then
  /usr/local/bin/dockutil --add "/Applications/Managed Software Center.app" \
                          --position beginning \
                          --label "Orchard Software Centre" \
                          --allhomes \
                          --no-restart
fi
