#!/bin/bash

PATH=/usr/sbin:/usr/local/bin:/usr/local/jamf/bin:${PATH}
ORCHARD_DEFAULTS=/Library/Preferences/uk.ac.ox.it.orchard
MUNKI_DEFAULTS=/Library/Preferences/ManagedInstalls
LOG_FILE=$(defaults read "${MUNKI_DEFAULTS}" LogFile)
LOG_DIR=$(dirname "${LOG_FILE}")
INSTALL_LOG_MTIME=$(stat -f "%m" "${LOG_DIR}/Install.log")

# Only run jamf recon if an Install/Removal has taken place
if [ $(defaults read "${ORCHARD_DEFAULTS}" InstallLogMtime) -ne $INSTALL_LOG_MTIME ];then
  jamf recon > /dev/null 2>&1 &
fi
