#!/bin/bash

DEFAULTS=/Library/Preferences/com.acme.lastinstalltime
MUNKI_DEFAULTS=/Library/Preferences/ManagedInstalls
LOG_FILE=$(defaults read "${MUNKI_DEFAULTS}" LogFile)
LOG_DIR=$(dirname "${LOG_FILE}")
INSTALL_LOG_MTIME=$(stat -f "%m" "${LOG_DIR}/Install.log")

defaults write "${DEFAULTS}" InstallLogMtime "${INSTALL_LOG_MTIME}"
